[phases.setup]
nixPkgs = ['nodejs-18_x', 'python312', 'python312Packages.pip']

[phases.install]
cmds = [
  'npm ci',
  'python3 -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install -r python-scripts/requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = '. /opt/venv/bin/activate && node app.js'
