[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'npm ci',
  'pip install -r python-scripts/requirements.txt'
]

[start]
cmd = 'node app.js'
